name: 03-Inputs con condición

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: "¿Cómo te llamas?"
        required: true
        default: "React developer en 2025"
      accion:
        description: "¿Qué quieres hacer?"
        required: true
        default: "saludar"
        type: choice
        options:
          - saludar
          - despedir

jobs:
  mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo
        if: ${{ github.event.inputs.accion == 'saludar' }}
        run: echo "Hola ${{ github.event.inputs.nombre }} 👋 ¡Espero que tengas un gran día!"

      - name: Despedida
        if: ${{ github.event.inputs.accion == 'despedir' }}
        run: echo "Adiós ${{ github.event.inputs.nombre }} 👋 ¡Nos vemos pronto!"
